### ISSUE TITLE
All URLs from all files are under one list in the logs

### ISSUE THREAD

**Issue by iriiiina** [paramt/url-checker#4]
Please don't list all URLs from all files in one bunch - it's a little bit hard to debug where exactly URL is broken if I have a lot of files. Is it possible to group URLs according to files in logs?

Instead of:
```
Collecting URLs from first.html
Collecting URLs from second.html
Checking all URLs
✓ 200 https://first.eu
✓ 200 https://second.eu
```

Something like this:
```
Collecting URLs from first.html
Collecting URLs from second.html
Checking URLs from first.html
✓ 200 https://first.eu
Checking URLs from second.html
✓ 200 https://second.eu
```

**Comment by paramt** [comment]
Thanks for the suggestion! Closed by 16550c91b6e808f7cd8e22b0df47174b047a967b
