### ISSUE TITLE
Blacklist links not working as it should

### ISSUE THREAD

**Issue by chowson** [paramt/url-checker#7]
Given the following text: "http://www.w3.org/1999/xhtml  http://www.sitemaps.org/schemas/sitemap/0.9"
    And Blacklist links "http://www.w3.org/1999/xhtml,http://www.sitemaps.org/schemas/sitemap/0.9"
Then "http://www.sitemaps.org/schemas/sitemap/0.9" is not removed from the text

I'm not a Python expert, but what I think happens is the first link is removed from the array, then the length of the list is 1, so the second one is not checked.

I've created a PR with a suggested fix - #8

**Comment by paramt** [comment]
Good catch!
