### ISSUE TITLE
add support for private repositories

### ISSUE THREAD

**Issue by georgettica** [paramt/url-checker#9]
currently, I tried to run this on a repository that cannot be accessed via `raw.githubusercontent.com`

this makes this command https://github.com/paramt/url-checker/blob/0abea3252caa144bd1e6b7786d715b6ff367a4be/check_links.py#L22
return an empty string and cause all of the actions to suceed

a solution for this is to pull the file using https://github.com/actions/github-script#download-data-from-a-url or just passing the token inside the script (as seen in this action)

this can be a separate script / repo as it's a different way of doing the same thing.

wanted to raise awareness to this because this action is super useful and I wanted it to be adopted some mote

**Comment by paramt** [comment]
Thanks for bringing this up - solved by #12
